### ISSUE TITLE
Clickable imports for lombok.

### ISSUE THREAD

**Issue by yoyosource** [OctoLinker/api#372]
Hello,

I would like to be able to navigate to the Lombok java doc in the projects.

I don't really know where to put the link I found for it in this repository, maybe somebody can do that for me or help me do it myself.

The link I found: 'http://projectlombok.org/api/allclasses-frame.html'

<img width="356" alt="image" src="https://user-images.githubusercontent.com/46222147/134924964-7abbaf28-d8c2-4524-b270-1c0209a03479.png">

Sincerely YoyoSource

**Comment by stefanbuck** [comment]
Hi, 

yeah this file is a little hidden, because it is so big 😄 The mapping is done in [mapping.json](https://github.com/OctoLinker/api/blob/master/src/java/mapping.json). This files is auto generate and therefore it might be better to adjust the script that generates this file https://github.com/OctoLinker/api/blob/master/scripts/update-mapping-files.js

This files is a scrapper that takes a Jdocs entrypoint as entry `allclasses-frame.htm` and then generates the mapping file. Do be honest, I haven't run this script in a while so it might be broken, produces a lot of changes (which is fine). Either-way, thanks for your contribution and let me know if you need help.

**Comment by yoyosource** [comment]
Hey,

so found the script thank you. Tried to run it worked fine for me. Now I will just add the desired links and create a Pull Request. If that is what is needed for it to update the clickability of Lombok imports.

Sincerely YoyoSource

**Comment by stefanbuck** [comment]
Yes that should it be, amazing thank you

**Comment by yoyosource** [comment]
I have one question, is it allowed to add my own project to the list of mapped files, or only projects that are well known?

The project I would add would be: https://github.com/yoyosource/YAPION

**Comment by yoyosource** [comment]
Also one more thing, the junit5 link does not work as it does not exist anymore.

**Comment by yoyosource** [comment]
Fixed the issue with junit5 by using an alternative link and creating a special selection code

**Comment by stefanbuck** [comment]
> I have one question, is it allowed to add my own project to the list of mapped files, or only projects that are well known?

All projects are welcome, so don't worry.

**Comment by yoyosource** [comment]
Also fixed an issue with the spring boot website. It changed and was a bit annoying to parse again

**Comment by yoyosource** [comment]
> All projects are welcome, so don't worry.
Sound amazing thanks.

**Comment by yoyosource** [comment]
I created my Pull Request as you probably already saw.
